dist: trusty
sudo: false
language: python
python:
- '3.6'
compiler:
- gcc
- clang
before_install: 
addons:
  apt:
    packages:
    - libxerces-c-dev
before_script:
- python --version
script:
- python setup.py build_ext -i
- python setup.py test
deploy:
  provider: pypi
  user: davidcaron
  password:
    secure: HXpMi87GNo1OX6nD/6swhdBDbgltOTUwClMp601BV1S62rjEEUzKNvoxWk1BlG/yoU5z8pIG5zT7R9aGmBlgfrRRt5quqB1YWWBYYsn7ZYeePfhS2LOoo317xwUNRMUV0jgLAWSgiFOMXzhXzkG4exX/V8Axqo36I+jS8QfIADxYNhogwv0ZNwuU4n79cQVioZmvwWJlMsVImwlOciXcC9Jau2MDVMknO1OZcmHR97AktjHw0Z0APgDu72FvA/fOMtf3IGtDN6BFi/Ptpt75SHYJeO/CTvYNm6I1V4CYbr8+QsvrDSaEx3kDSPnxM+h2YwC5eHJ8Rhk2cWPWlbLnEuWS3rCfSPKRjC5sTc96HwxyWeMrBeURGi2X86rCWwv91Lp0uL/DVDexyftzVWYIktjk9cwXLpNB0W018HsHF4xeAgVFaRyDkeTnNerHHGjzL0dgakPeBEE3XkQK8Kh5VlReY23hc2GgzMUYMZnJ4dmvMfmi5V5BWKgGoE7CYYHQS/shQZ+9Wvr5R0liLe38lP4tW4USRgw8P6TQS3DvGnkrOeIXiDPMhg9h5HiaOEt20eKFZQB1wysVIphcb56dOPQqmX9hghAfNyGE1lePZZXi02DQ7CciXTj/Rybk+cg+b0RhOfY0Mg98HCrxAQe67MiRPr79MQP3uJOjMJpZKkQ=
  on:
    tags: true
